version: "3"

services:
  commande:
    image: node
    ports:
      - "3000:3000"
    env_file:
      - ./commande/.env.dev
    volumes:
      - ./commande:/usr/src/app
    working_dir: /usr/src/app
    #command: npm start
    #command: bash -c 'npm -i && npm start'
    command: bash -c 'npm i && npm run dev'
    links:
      - mysql
  mysql:
    image: mariadb
    env_file:
      - ./mysql/.env.dev
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  adminer:
    image: adminer
    ports:
      - "3001:8080"
    restart: always
    links:
      - mysql
