version: "3"

services:
  api.commande:
    container_name: api.commande
    image: node
    ports:
      - "19080:3000"
    env_file:
      - ./commande/.env.dev
    volumes:
      - ./commande:/usr/src/app
      - ./commande/node_modules:/usr/src/outside/node_modules
    working_dir: /usr/src/app
    command: bash -c 'npm i && npm run dev'
    links:
      - mysql.commande
  mysql.commande:
    image: mariadb:latest
    container_name: mysql.commande
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
      - ./mysql/.env.dev
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  adminer.commande:
    image: adminer
    container_name: adminer.commande
    ports:
      - 8080:8080
    links:
      - mysql.commande